[workspace]
members = ["./packages/minimp4", "./packages/minimp4-sys"]
resolver = "2"

[workspace.dependencies]
minimp4-sys = { workspace = true, path = "packages/minimp4-sys" }

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
strip = "symbols"
